# +————————————————————————————————————————————————+ #
# |————————  EVENTDISABLER CONFIGURATION   ————————| #
# |————————————————      v1        ————————————————| #
# +————————————————————————————————————————————————+ #
#
# List of disabled events:
disabled:
#- 'VillagerAcquireTradeEvent'
#- 'ItemMergeEvent'
