# +————————————————————————————————————————————————+ #
# |————————  EVENTDISABLER CONFIGURATION   ————————| #
# |————————————————      v1        ————————————————| #
# +————————————————————————————————————————————————+ #
#
# List of disabled events:
# The list contains list of worlds where the event will be disabled.
disabled:
#  VillagerAcquireTradeEvent:
#    - 'world'
#  ItemMergeEvent:
#    - '*'