name: EventDisabler
main: fr.andross.eventdisabler.Plugin
version: '1.2'
author: _Andross
description: Disable any bukkit event
commands:
  eventdisabler:
    description: Main command for the plugin. Display help.
    aliases: [ed]
premissions:
  eventdisabler.reload:
    description: reload the config
