name: EventDisabler
main: fr.andross.eventdisabler.EventDisabler
version: '1.5'
api-version: '1.13'
author: _Andross
description: Disable any bukkit event
commands:
  eventdisabler:
    description: reload the configuration
    permission: eventdisabler.reload
    aliases: [ed]
